/**
 * Structural pre-launch validation. Release-grade check — runs in validate:launch,
 * not in validate (PR-grade). Fails fast on placeholder values that must be replaced
 * before a site goes live.
 *
 * Rules:
 *   - No placeholder strings in config files (site.ts, config.yml, site.webmanifest)
 *   - og-default.png must NOT be the template placeholder (hash check)
 *   - Production URL must be HTTPS, not localhost/example/127.0.0.1
 *
 * Does NOT make network requests. Post-deploy reachability is in docs/deployment/runbook.md.
 *
 * Run: bun run check:launch
 */

import { site } from '../src/lib/config/site';
import { REQUIRED_PUBLIC_ENV_VARS, REQUIRED_PRIVATE_ENV_VARS } from '../src/lib/server/env';
import { readFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';

// Hash of the placeholder og-default.png generated by scripts/generate-placeholder-assets.ts.
// If og-default.png matches this hash, the image hasn't been replaced.
const OG_PLACEHOLDER_HASH = 'e0597a81489d31513a5488151287ec107ae9deabf6b0c99399643e6bdbf587ab';

// Domains / values that indicate a file hasn't been customised yet.
const FORBIDDEN_DOMAINS = ['localhost', '127.0.0.1', 'example.com', 'example.org', '0.0.0.0'];
const FORBIDDEN_STRINGS = [
	'Your Site Name',
	'https://example.com',
	'owner/repo-name',
	'REPLACE PER PROJECT',
	'[Site Title]',
	'[Site Name]',
	'[Year]',
];

// Files to scan for forbidden placeholder strings.
const CONFIG_FILES: Array<{ path: string; label: string }> = [
	{ path: 'src/lib/config/site.ts', label: 'site config' },
	{ path: 'src/app.html', label: 'app shell' },
	{ path: 'src/routes/+layout.svelte', label: 'root layout' },
	{ path: 'static/admin/config.yml', label: 'CMS config' },
	{ path: 'static/site.webmanifest', label: 'web manifest' },
];

// Required environment variables — sourced from src/lib/server/env.ts schemas.
// Importing only the constant arrays; Valibot validation is NOT triggered here.
const REQUIRED_ENV_VARS = [...REQUIRED_PUBLIC_ENV_VARS, ...REQUIRED_PRIVATE_ENV_VARS];

const errors: string[] = [];
const warnings: string[] = [];

// ── 1. Placeholder string scan ────────────────────────────────────────────────

for (const { path, label } of CONFIG_FILES) {
	if (!existsSync(path)) {
		warnings.push(`${label}: file not found at ${path} — skipping placeholder scan`);
		continue;
	}
	const content = readFileSync(path, 'utf-8');
	for (const needle of FORBIDDEN_STRINGS) {
		if (content.includes(needle)) {
			errors.push(`${label} (${path}) contains placeholder: "${needle}"`);
		}
	}
}

// ── 2. OG image hash check ────────────────────────────────────────────────────

if (existsSync('static/og-default.png')) {
	const buf = readFileSync('static/og-default.png');
	const hash = createHash('sha256').update(buf).digest('hex');
	if (hash === OG_PLACEHOLDER_HASH) {
		errors.push(
			'static/og-default.png is still the template placeholder — replace it with a real OG image before launch'
		);
	}
} else {
	errors.push('static/og-default.png is missing — run check:assets to identify all missing assets');
}

// ── 3. Production URL validation ──────────────────────────────────────────────

const prodUrl = site.url;

if (!prodUrl) {
	errors.push('site.url is empty — set a production URL in src/lib/config/site.ts');
} else {
	let parsed: URL | null = null;
	try {
		parsed = new URL(prodUrl);
	} catch {
		errors.push(`site.url "${prodUrl}" is not a valid URL`);
	}

	if (parsed) {
		if (parsed.protocol !== 'https:') {
			errors.push(`site.url "${prodUrl}" must use HTTPS — got "${parsed.protocol}"`);
		}
		const hostname = parsed.hostname;
		for (const forbidden of FORBIDDEN_DOMAINS) {
			if (
				hostname === forbidden ||
				hostname.endsWith(`.${forbidden}`) ||
				hostname.endsWith('.local')
			) {
				errors.push(
					`site.url "${prodUrl}" uses a forbidden hostname "${hostname}" — must be a real production domain`
				);
				break;
			}
		}
	}
}

// ── 4. Required env vars (sourced from src/lib/server/env.ts schemas) ────────

for (const envVar of REQUIRED_ENV_VARS) {
	if (!process.env[envVar]) {
		warnings.push(`Environment variable ${envVar} is not set — required for production`);
	}
}

// ── Report ────────────────────────────────────────────────────────────────────

if (warnings.length) {
	console.warn('\nWarnings:');
	for (const w of warnings) console.warn(`  ⚠  ${w}`);
}

if (errors.length) {
	console.error('\ncheck:launch failed — the following issues must be fixed before launch:\n');
	for (const e of errors) console.error(`  ✗  ${e}`);
	console.error(
		`\n${errors.length} issue(s) found. Run "bun run init:site" to fix most of these automatically.`
	);
	process.exit(1);
} else {
	console.log('✓ check:launch passed — no placeholder values detected.');
	if (warnings.length) {
		console.log('  (see warnings above — they are non-blocking for this check)');
	}
}
