/**
 * Structural pre-launch validation. Release-grade check — runs in validate:launch,
 * not in validate (PR-grade). Fails fast on placeholder values that must be replaced
 * before a site goes live.
 *
 * Rules:
 *   - No launch-blocking placeholders in config, deploy, and env example files
 *   - og-default.png must NOT be the template placeholder (hash check)
 *   - Production URLs must be HTTPS, not localhost/example/127.0.0.1
 *
 * Does NOT make network requests. Post-deploy reachability is in docs/deployment/runbook.md.
 *
 * Run: bun run check:launch
 */

import { site } from '../src/lib/config/site';
import { REQUIRED_PUBLIC_ENV_VARS, REQUIRED_PRIVATE_ENV_VARS } from '../src/lib/server/env';
import { readFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';

// Hash of the placeholder og-default.png generated by scripts/generate-placeholder-assets.ts.
// If og-default.png matches this hash, the image hasn't been replaced.
const OG_PLACEHOLDER_HASH = 'e0597a81489d31513a5488151287ec107ae9deabf6b0c99399643e6bdbf587ab';

// Domains / values that indicate a file hasn't been customised yet.
const FORBIDDEN_DOMAINS = ['localhost', '127.0.0.1', 'example.com', 'example.org', '0.0.0.0'];
const FORBIDDEN_STRINGS = [
	'Your Site Name',
	'https://example.com',
	'owner/repo-name',
	'REPLACE PER PROJECT',
	'[Site Title]',
	'[Site Name]',
	'[Year]',
];

const DEPLOY_FORBIDDEN_STRINGS = [...FORBIDDEN_STRINGS, '<owner>', '<name>', '<project>'];

type ScanKind = 'src-static' | 'deploy' | 'env-example';

const SCANNED_FILES: Array<{ path: string; label: string; kind: ScanKind }> = [
	{ path: 'src/lib/config/site.ts', label: 'site config', kind: 'src-static' },
	{ path: 'src/app.html', label: 'app shell', kind: 'src-static' },
	{ path: 'src/routes/+layout.svelte', label: 'root layout', kind: 'src-static' },
	{ path: 'static/admin/config.yml', label: 'CMS config', kind: 'src-static' },
	{ path: 'static/site.webmanifest', label: 'web manifest', kind: 'src-static' },
	{ path: 'deploy/Caddyfile.example', label: 'Caddyfile example', kind: 'deploy' },
	{ path: 'deploy/quadlets/web.container', label: 'web Quadlet', kind: 'deploy' },
	{ path: 'deploy/quadlets/web.network', label: 'network Quadlet', kind: 'deploy' },
	{ path: '.env.example', label: 'local env example', kind: 'env-example' },
	{ path: 'deploy/env.example', label: 'deploy env example', kind: 'env-example' },
];

// Required environment variables — sourced from src/lib/server/env.ts schemas.
// Importing only the constant arrays; Valibot validation is NOT triggered here.
const REQUIRED_ENV_VARS = [...REQUIRED_PUBLIC_ENV_VARS, ...REQUIRED_PRIVATE_ENV_VARS];

const errors: string[] = [];
const warnings: string[] = [];

function hasForbiddenHostname(hostname: string): boolean {
	return FORBIDDEN_DOMAINS.some(
		(forbidden) =>
			hostname === forbidden || hostname.endsWith(`.${forbidden}`) || hostname.endsWith('.local')
	);
}

function validateProductionUrl(value: string, label: string): void {
	let parsed: URL;
	try {
		parsed = new URL(value);
	} catch {
		errors.push(`${label} "${value}" is not a valid URL`);
		return;
	}

	if (parsed.protocol !== 'https:') {
		errors.push(`${label} "${value}" must use HTTPS — got "${parsed.protocol}"`);
	}

	if (hasForbiddenHostname(parsed.hostname)) {
		errors.push(
			`${label} "${value}" uses a forbidden hostname "${parsed.hostname}" — must be a real production domain`
		);
	}
}

// ── 1. Placeholder string scan ────────────────────────────────────────────────

for (const { path, label, kind } of SCANNED_FILES) {
	if (!existsSync(path)) {
		warnings.push(`${label}: file not found at ${path} — skipping placeholder scan`);
		continue;
	}
	const content = readFileSync(path, 'utf-8');
	const forbiddenStrings = kind === 'deploy' ? DEPLOY_FORBIDDEN_STRINGS : FORBIDDEN_STRINGS;
	for (const needle of kind === 'env-example' ? [] : forbiddenStrings) {
		if (content.includes(needle)) {
			errors.push(`${label} (${path}) contains placeholder: "${needle}"`);
		}
	}

	if (kind === 'deploy') {
		for (const line of content.split(/\r?\n/)) {
			if (/^\s*Image=.*example\.com/.test(line)) {
				errors.push(`${label} (${path}) contains example.com in Image= line`);
			}
			if (/^\s*(?:www\.)?[a-z0-9.-]*example\.com[a-z0-9.-]*\s*\{/.test(line)) {
				errors.push(`${label} (${path}) contains example.com in a domain block`);
			}
		}
		if (content.includes('Replace example.com with the real domain before use.')) {
			errors.push(`${label} (${path}) contains the placeholder Caddy header`);
		}
	}

	if (kind === 'env-example') {
		for (const envVar of ['ORIGIN', 'PUBLIC_SITE_URL']) {
			const pattern = new RegExp(`^${envVar}=https://example\\.com\\s*$`, 'm');
			if (pattern.test(content)) {
				errors.push(`${label} (${path}) contains placeholder ${envVar}=https://example.com`);
			}
		}
	}
}

// ── 2. OG image hash check ────────────────────────────────────────────────────

if (existsSync('static/og-default.png')) {
	const buf = readFileSync('static/og-default.png');
	const hash = createHash('sha256').update(buf).digest('hex');
	if (hash === OG_PLACEHOLDER_HASH) {
		errors.push(
			'static/og-default.png is still the template placeholder — replace it with a real OG image before launch'
		);
	}
} else {
	errors.push('static/og-default.png is missing — run check:assets to identify all missing assets');
}

// ── 3. Production URL validation ──────────────────────────────────────────────

if (!site.url) {
	errors.push('site.url is empty — set a production URL in src/lib/config/site.ts');
} else {
	validateProductionUrl(site.url, 'site.url');
}

// ── 4. Required env vars (sourced from src/lib/server/env.ts schemas) ────────

for (const envVar of REQUIRED_ENV_VARS) {
	const value = process.env[envVar];
	if (!value) {
		warnings.push(`Environment variable ${envVar} is not set — required for production`);
	} else if (envVar === 'ORIGIN' || envVar === 'PUBLIC_SITE_URL') {
		validateProductionUrl(value, `Environment variable ${envVar}`);
	}
}

// ── Report ────────────────────────────────────────────────────────────────────

if (warnings.length) {
	console.warn('\nWarnings:');
	for (const w of warnings) console.warn(`  ⚠  ${w}`);
}

if (errors.length) {
	console.error('\ncheck:launch failed — the following issues must be fixed before launch:\n');
	for (const e of errors) console.error(`  ✗  ${e}`);
	console.error(
		`\n${errors.length} issue(s) found. Run "bun run init:site" to fix most of these automatically.`
	);
	process.exit(1);
} else {
	console.log('✓ check:launch passed — no placeholder values detected.');
	if (warnings.length) {
		console.log('  (see warnings above — they are non-blocking for this check)');
	}
}
